before:
  hooks:
    - go mod tidy -v
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
      - mipsle
      - s390x
      - riscv64
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: .
    binary: nbdns
universal_binaries:
  - name_template: "nbdns"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "nbdns"
archives:
  - name_template: "nbdns_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/naiba/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/naiba/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/naiba/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/naiba/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/naiba/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/naiba/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/naiba/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/naiba/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/naiba/{{ .ProjectName }}:latest-amd64
      - ghcr.io/naiba/{{ .ProjectName }}:latest-arm64v8
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
